step1: step1.c step2.c step3.c
	gcc -std=gnu99 -Wall -Werror -pedantic -o step1 step1.c
	gcc -std=gnu99 -Wall -Werror -pedantic -o step2 step2.c
	gcc -std=gnu99 -Wall -Werror -pedantic -o step3 step3.c


